name = "QuestDB"
uuid = "c409e7dc-95dd-4f76-9030-daa6b84467ba"
authors = ["Brandon Escamilla <brandon.escamilla@outlook.com>"]
version = "0.1.0"

[deps]
CEnum = "fa961155-64e5-5f13-b03f-caf6b980ea82"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
PyCall = "438e738f-606a-5dbb-bf0a-cddfbfd45ab0"
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"
c_questdb_client_jll = "49a0df60-3d80-5428-85ce-5c0f24fd7b67"
